const en_US = {
  title: 'Data sources',
  search_placeholder: 'Please enter search keywords',
  chooseDataSourceType: 'Choose data source type',
  name: 'Data source name',
  id: 'Data source ID',
  description: 'Description',
  type: 'Type',
  enable: 'Enable',
  disable: 'Disable',
  confirm: {
    enable: 'Are you sure you want to enable this data source?',
    disable: 'Are you sure you want to disable this data source?',
  },
  success: {
    enable: 'Enable successfully',
    disable: 'Disable successfully',
  },
  add_title: 'Add data source',
  edit_title: 'Edit data source',
  rename_title: 'Rename',
  type_btn_add: 'Add',
  default: 'Set as default',
  default_msg: 'The default cluster under this data source type, the time series data collected by the network detection function will be reported to this data source',
  default_tip: 'The time series data collected by the network detection function will be reported to this data source',
  auth: {
    name: 'Auth',
    'not-support': 'Not support',
  },
  status: {
    title: 'Status',
    enabled: 'Enabled',
    disabled: 'Disabled',
  },
  form: {
    other: 'Other',
    name: 'Name',
    name_msg: 'Please enter letters,numbers,underscores, must start with a letter',
    name_msg2: 'At least 3 characters',
    identifier: 'Identifier',
    timeout: 'Timeout(ms)',
    auth: 'Auth',
    username: 'User',
    password: 'Password',
    skip_ssl_verify: 'Skip SSL verify',
    skip_tls_verify: 'Skip TLS verify',
    yes: 'Yes',
    no: 'No',
    headers: 'Custom HTTP headers',
    description: 'Description',
    cluster: 'Cluster',
    cluster_tip:
      'In the architecture of multiple data centers, sometimes multiple alerting engine clusters are deployed. Corresponding to the data source of the edge data center, it is necessary to associate the alerting engine cluster of the corresponding data center. If there is only one cluster, keep the default',
    cluster_confirm:
      'Your data source is not associated with an alerting engine cluster. It will not be able to be used for alerting. Do you want to associate an alerting engine cluster?',
    cluster_confirm_ok: 'No association',
    cluster_confirm_cancel: 'Associate',
    url_no_spaces_msg: 'Spaces are not allowed in the URL',
    prom: {
      write_addr_tip: 'Write address of the data generated by the recording rule',
      read_addr: 'Internal address of the time series database',
      read_addr_tip:
        'Usually used in the scenario of deploying the alerting engine in the edge data center. If this field is not empty, n9e-edge will use this address to access the time series database. If this field is empty, n9e-edge will use the URL above to access the time series database',
      url_tip: 'Common time series database configuration examples (compatible with Prometheus query API):',
      help_content: 'Not deployed a time series database? Refer to the <a>installation manual</a> for installation and deployment',
      prom_installation_title: 'Installation',
      prom_installation:
        'On the machine where n9e is deployed, run the following command to install the Prometheus time series database. For production environments, it is recommended to deploy the cluster version of VictoriaMetrics. Refer to the <a>official documentation</a> for details',
      tsdb_type: 'Time series database type',
    },
    es: {
      enable_write: 'Enable Write',
      version: 'Version',
      max_shard: 'Max concurrent Shard Requests',
      min_interval: 'Min time interval(s)',
      min_interval_tip:
        'The lower bound for automatic grouping based on time intervals. It is recommended to set it to the write frequency. For example, if data is written every minute, it should be set as 1m',
    },
    jaeger: {
      version: 'Version',
    },
    ck: {
      title: 'Database basic information',
      addr: 'Database address',
    },
    sls: {
      title: 'Service entry',
      endpoint: 'Access domain name (private network domain name / public network domain name / cross-domain domain name)',
      access: 'Access',
      endpoint_link: 'Configuration instructions',
    },
    os: {
      title: 'OpenSearch Settings',
      enable_write_title: 'Enable write',
      enable_write: 'Enable write',
    },
  },
};
export default en_US;
