export const DARK_PARAMS = {
  accentColor: '#FFFFFF',
  borderColor: '#CCCCDC1F',
  borderRadius: 0,
  browserColorScheme: 'dark',
  cellHorizontalPaddingScale: 1.4,
  chromeBackgroundColor: {
    ref: 'backgroundColor',
  },
  columnBorder: true,
  fontSize: 12,
  foregroundColor: '#CCCCDC',
  headerBackgroundColor: '#FFFFFF00',
  headerFontSize: 14,
  headerFontWeight: 500,
  headerRowBorder: true,
  headerTextColor: '#CCCCDC',
  headerVerticalPaddingScale: 0.9,
  rowBorder: true,
  rowVerticalPaddingScale: 1.4,
  sidePanelBorder: true,
  spacing: 3,
  wrapperBorder: false,
  wrapperBorderRadius: 0,
};

export const LIGHT_PARAMS = {
  accentColor: '#333333',
  borderColor: '#24292e1f',
  borderRadius: 0,
  browserColorScheme: 'light',
  cellHorizontalPaddingScale: 1.4,
  columnBorder: true,
  fontSize: 12,
  foregroundColor: '#262626',
  headerBackgroundColor: '#FFFFFF00',
  headerFontSize: 14,
  headerFontWeight: 500,
  headerRowBorder: true,
  headerTextColor: '#262626',
  headerVerticalPaddingScale: 0.9,
  rowBorder: true,
  rowVerticalPaddingScale: 1.4,
  sidePanelBorder: true,
  spacing: 3,
  wrapperBorder: false,
  wrapperBorderRadius: 0,
};
