export const NUMBER_TYPES = ['BOOLEAN', 'TINYINT', 'SMALLINT', 'INT', 'BIGINT', 'LARGEINT', 'FLOAT', 'DOUBLE', 'DECIMAL'];
export const DATE_TYPES = ['DATE', 'DATETIME'];
export const STRING_TYPES = ['CHAR', 'VARCHAR', 'STRING'];
export const JSON_TYPES = ['JSON'];
export const VARIANT_TYPES = ['VARIANT'];
export const COMPOSITE_TYPES = ['ARRAY', 'MAP', 'STRUCT'];
export const IP_TYPES = ['IPv4', 'IPv6'];

export const EQUAL_OPERATORS = ['=', '!='];
export const IN_OPERATORS = ['IN', 'NOT IN'];
export const NULL_OPERATORS = ['IS NULL', 'IS NOT NULL'];
export const BETWEEN_OPERATORS = ['BETWEEN AND', 'NOT BETWEEN AND'];
export const LIKE_OPERATORS = ['LIKE', 'NOT LIKE'];
export const MATCH_OPERATORS = [
  'MATCH',
  'MATCH_ALL',
  'MATCH_PHRASE',
  'MATCH_PHRASE_PREFIX',
  'MATCH_PHRASE_EDGE',
  'MATCH_REGEX',
  'NOT MATCH',
  'NOT MATCH_ALL',
  'NOT MATCH_PHRASE',
  'NOT MATCH_PHRASE_PREFIX',
  'NOT MATCH_PHRASE_EDGE',
  'NOT MATCH_REGEX',
];
const BASE_OPERATORS = [...EQUAL_OPERATORS, ...IN_OPERATORS, ...NULL_OPERATORS, ...BETWEEN_OPERATORS];

const NUMBER_TYPE_OPERATORS = BASE_OPERATORS;
const DATE_TYPE_OPERATORS = BASE_OPERATORS;
const STRING_TYPE_OPERATORS = [...EQUAL_OPERATORS, ...LIKE_OPERATORS, ...IN_OPERATORS, ...NULL_OPERATORS, ...BETWEEN_OPERATORS, ...MATCH_OPERATORS];
const JSON_TYPE_OPERATORS = NULL_OPERATORS;
const VARIANT_TYPE_OPERATORS = NULL_OPERATORS;
const COMPOSITE_TYPE_OPERATORS = NULL_OPERATORS;
const IP_TYPE_OPERATORS = BASE_OPERATORS;

export const TYPE_OPERATOR_MAP = {
  // NUMBER_TYPE_OPERATORS
  BOOLEAN: NUMBER_TYPE_OPERATORS,
  TINYINT: NUMBER_TYPE_OPERATORS,
  SMALLINT: NUMBER_TYPE_OPERATORS,
  INT: NUMBER_TYPE_OPERATORS,
  BIGINT: NUMBER_TYPE_OPERATORS,
  LARGEINT: NUMBER_TYPE_OPERATORS,
  FLOAT: NUMBER_TYPE_OPERATORS,
  DOUBLE: NUMBER_TYPE_OPERATORS,
  DECIMAL: NUMBER_TYPE_OPERATORS,

  // DATE_TYPE_OPERATORS
  DATE: DATE_TYPE_OPERATORS,
  DATETIME: DATE_TYPE_OPERATORS,

  // STRING_TYPE_OPERATORS
  CHAR: STRING_TYPE_OPERATORS,
  VARCHAR: STRING_TYPE_OPERATORS,
  STRING: STRING_TYPE_OPERATORS,

  // JSON_TYPE_OPERATORS
  JSON: JSON_TYPE_OPERATORS,

  // VARIANT_TYPE_OPERATORS
  VARIANT: VARIANT_TYPE_OPERATORS,

  // COMPOSITE_TYPE_OPERATORS
  ARRAY: COMPOSITE_TYPE_OPERATORS,
  MAP: COMPOSITE_TYPE_OPERATORS,
  STRUCT: COMPOSITE_TYPE_OPERATORS,

  // IP_TYPE_OPERATORS
  IPv4: IP_TYPE_OPERATORS,
  IPv6: IP_TYPE_OPERATORS,
};

export const AGGREGATE_FUNCTION_TYPE_MAP = {
  COUNT: [...NUMBER_TYPES, ...DATE_TYPES, ...STRING_TYPES, ...IP_TYPES],
  AVG: NUMBER_TYPES,
  MAX: NUMBER_TYPES,
  MIN: NUMBER_TYPES,
  SUM: NUMBER_TYPES,
  PERCENTILE: NUMBER_TYPES,
  UNIQUE_COUNT: [...NUMBER_TYPES, ...DATE_TYPES, ...STRING_TYPES, ...IP_TYPES],
  EXIST_RATIO: [...NUMBER_TYPES, ...DATE_TYPES, ...STRING_TYPES, ...IP_TYPES],
  TOPN: [...NUMBER_TYPES, ...DATE_TYPES, ...STRING_TYPES, ...IP_TYPES],
};
